site_name: Monsterhearts
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple

extra_css:
  - css/main.css
markdown_extensions:
  - attr_list
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - ezlinks
  - autolinks 
  - callouts