name: Build and deploy

on:
  workflow_dispatch: # Allow manual triggers
  push:
    tags-ignore:
      - '**' # Ignore any tags here
    branches:
      - main
    #
    # Trigger when either files in the docs folder,
    # the requirements.txt file or the mkdocs.yml file
    # are edited and commited.
    paths:
      - '**'
      - 'docs/**'
      - 'mkdocs.yml'

# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: write

# Makes sure only one workflow runs at a time.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    # This environment is required!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: '3.x' # Uses latest 3.x version.
      - name: Install dependencies
        # Alternatively: pip install mkdocs
        run: pip install mkdocs mkdocs-material mkdocs-ezlinks-plugin mkdocs-autolinks-plugin mkdocs-callouts
      - name: Build Docs
        run: cd ./mh-wiki/ && mkdocs build && mkdocs gh-serve --force